inherit_mode:
  merge:
    - Exclude
    - CountAsOne

AllCops:
  Exclude:
    - 'lib/handlebars_lexer.rb'
    - 'lib/handlebars_parser.rb'
  NewCops: enable
  TargetRubyVersion: 3.0

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes
