inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude
    - CountAsOne

AllCops:
  Exclude:
    - 'lib/handlebars_lexer.rb'
    - 'lib/handlebars_parser.rb'
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/FirstHashElementIndentation:
  Exclude:
    - 'test/compatibility/*'

Layout/FirstArrayElementIndentation:
  Exclude:
    - 'test/compatibility/*'

Layout/LineLength:
  Max: 92
  Exclude:
    - 'test/compatibility/*'

# Assume the programmer knows how bracketed block syntax works
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Test describe blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Naming/MethodParameterName:
  AllowedNames:
    - fn

Naming/VariableName:
  Exclude:
    - 'test/compatibility/*'

Style/GuardClause:
  Exclude:
    - 'test/compatibility/*'

Style/DoubleNegation:
  Exclude:
    - 'test/compatibility/*'

Style/IfUnlessModifier:
  Exclude:
    - 'test/compatibility/*'

Style/LineEndConcatenation:
  Exclude:
    - 'test/compatibility/*'

Style/NegatedIf:
  Exclude:
    - 'test/compatibility/*'

Style/NumericPredicate:
  Enabled: false

Style/QuotedSymbols:
  Exclude:
    - 'test/compatibility/*'

Style/RedundantReturn:
  AllowMultipleReturnValues: true
  Exclude:
    - 'test/compatibility/*'

Style/RegexpLiteral:
  Exclude:
    - 'test/compatibility/*'

Style/Semicolon:
  Exclude:
    - 'test/compatibility/*'

Style/ZeroLengthPredicate:
  Exclude:
    - 'test/compatibility/*'

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'test/compatibility/*'

Style/StringConcatenation:
  Exclude:
    - 'test/compatibility/*'

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'test/compatibility/*'

Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'test/compatibility/*'

Style/WordArray:
  Exclude:
    - 'test/compatibility/*'
