inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude
    - CountAsOne

AllCops:
  Exclude:
    - 'lib/handlebars_lexer.rb'
    - 'lib/handlebars_parser.rb'
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/FirstHashElementIndentation:
  Exclude:
    - 'test/compatibility/*'

# Test describe blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

# Assume the programmer knows how bracketed block syntax works
Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'test/compatibility/*'

Style/RedundantReturn:
  Exclude:
    - 'test/compatibility/*'

Style/Semicolon:
  Exclude:
    - 'test/compatibility/*'

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'test/compatibility/*'

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'test/compatibility/*'

Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'test/compatibility/*'
